### ISSUE TITLE
Broke the AppleScript that connects Tyme2 and Omnifocus

### ISSUE THREAD

**Issue by jktzes** [patrickkahl/alfred-tyme#1]
Constantly getting error 

> The operation couldn’t be completed. /Users/Ezo/Library/Application Scripts/com.omnigroup.OmniFocus2/omni2tyme.applescript:1177:1525: execution error: Tyme2 got an error: AppleEvent handler failed. (-10000

when running the AppleScript from Omnifocus

**Comment by kahl-dev** [comment]
There was a bug in Tyme. Please update to the newest version which came out today because they fixed it.
